/**
 * Some features used by Angular are not yet supported natively by all major browsers, 
 * polyfills are used to add support for features where necessary so 
 * your Angular boilerplate application works across all major browsers.
This file is generated by the Angular CLI when creating a new project with the 
ng new command, I've excluded the comments in the file for brevity.
 */
import 'zone.js';  // Included with Angular CLI.
